server:
  port:8080
  contextPath=/html

spring:
    datasource:
        name: huzhou
        url: jdbc:mysql://rm-uf6zfc3uaa30t5820qo.mysql.rds.aliyuncs.com:3306/huzhou?characterEncoding=UTF-8
        username: huzhou_jiaojing
        password: HuZhouJiaoJing@123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapperLocations: classpath:mapper/*.xml # 注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.hodehtml.demo.model  # 注意：对应实体类的路径
  configuration:
    cache-enabled: true

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  pattern:
    console : "%d - %msg%n"
  path: /日志/log
  file: /日志/log
  level:
    com.hodehtml.demo.dao: debug
